version: '3'
services:
  # clickhouse:
  #   image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
  #   container_name: clickhouse
  #   environment:
  #     - CLICKHOUSE_USER=${CLICKHOUSE_USER}
  #     - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
  #     - CLICKHOUSE_DB=${CLICKHOUSE_DB}
  #   ports:
  #     - '8123:8123'
  #   volumes:
  #     - clickhouse:/var/lib/clickhouse
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis
volumes:
  # clickhouse:
  mysql:
  redis:
